package postgresql

import (
	"crud/domain"
	"database/sql"
	"log"
)

type PersonRepository struct {
	db *sql.DB
}

func NewPersonRepository(db *sql.DB) (*PersonRepository, error) {
	return &PersonRepository{
		db: db,
	}, nil
}

func (pr *PersonRepository) TableCreateQuery() error {
	_, err := pr.db.Exec("CREATE TABLE IF NOT EXISTS persontable (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, email TEXT, phone TEXT, firstName TEXT, lastName TEXT)")
	if err != nil {
		log.Println(err)
		return err
	}
	return nil
}

func (pr *PersonRepository) PostPersonQuery(p domain.Person) error {

	result, err := pr.db.Exec("INSERT INTO persontable (email, phone, firstName, lastName) VALUES ($1,$2,$3,$4)", p.Email, p.Phone, p.FirstName, p.LastName)
	if err != nil {
		log.Println("DB error", err)
		return err
	}

	id, _ := result.LastInsertId()
	p.Id = int(id)

	return nil
}

func (pr *PersonRepository) GetPersonQuery() ([]domain.Person, error) {

	rows, err := pr.db.Query("SELECT * FROM persontable")
	if err != nil {
		log.Println("DB error", err)
		return nil, err
	}

	defer rows.Close()

	var sliceperson []domain.Person

	for rows.Next() {

		var p domain.Person

		err = rows.Scan(&p.Id, &p.Email, &p.Phone, &p.FirstName, &p.LastName)
		if err != nil {
			log.Println("DB error", err)
			return nil, err
		}

		sliceperson = append(sliceperson, p)
	}

	err = rows.Err()
	if err != nil {
		log.Println("DB error", err)
		return nil, err
	}

	return sliceperson, nil
}

func (pr *PersonRepository) GetPersonIdQuery(id int) (domain.Person, error) {

	row := pr.db.QueryRow("SELECT * FROM persontable WHERE id=$1", id)

	var p domain.Person

	err := row.Scan(&p.Id, &p.Email, &p.Phone, &p.FirstName, &p.LastName)
	if err != nil {
		log.Println("DB error", err)
		return domain.Person{}, err
	}

	return p, nil
}

func (pr *PersonRepository) PutPersonIdQuery(id int, p domain.Person) error {

	_, err := pr.db.Exec("UPDATE persontable SET email=$1, phone=$2, firstName=$3, lastName=$4 WHERE id=$5", p.Email, p.Phone, p.FirstName, p.LastName, id)
	if err != nil {
		log.Println("DB error", err)
		return err
	}

	return nil
}

func (pr *PersonRepository) DelPersonIdQuery(id int) error {

	_, err := pr.db.Exec("DELETE FROM persontable WHERE id=$1", id)
	if err != nil {
		log.Println("DB error", err)
		return err
	}

	return nil
}
